version: "3"

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: dockerfile
    ports:
      - "80:80"
  webservice:
    build:
      context: ./webservice
      dockerfile: dockerfile
